[package]
name = "dockrs"
description = "A CLI for interacting with a Docker daemon"
version = "0.1.0"
edition = "2021"
license = "MIT or APACHE-2.0"
repository = "https://github.com/joshuachp/dockrs"
keywords = ["docker", "cli"]
categories = ["command-line-interface"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
